### ISSUE TITLE
Error on pushing init branch

### ISSUE THREAD

**Issue by hsonne** [technologiestiftung/fhpredict#3]
Hi @fabianmoronzirfas,

when pushing my init branch I got the following error. What does that mean? The branch was created in our repository, anyway...

```
C:\Users\hsonne\Documents\github-repos\fhpredict>git push origin init
Counting objects: 20, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (20/20), 4.24 KiB | 867.00 KiB/s, done.
Total 20 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
remote:
remote: Create a pull request for 'init' on GitHub by visiting:
remote:      https://github.com/technologiestiftung/fhpredict/pull/new/init
remote:
To https://github.com/technologiestiftung/fhpredict
 * [new branch]      init -> init
error: update_ref failed for ref 'refs/remotes/origin/init': cannot lock ref 'refs/remotes/origin/init': 'refs/remotes/orig
in/init/travis' exists; cannot create 'refs/remotes/origin/init'
```

**Comment by fabianmoronzirfas** [comment]
@hsonne wired. Might be a naming problem. The branch I created before was named `init/travis` so maybe the pure `init` clashes with that. But the branch exists. Can you test if you can push something else to that branch without getting this error?

**Comment by hsonne** [comment]
Same error when pushing d2d0633. But the change arrives. So I will take care not to use conflicting names in the future.

**Comment by fabianmoronzirfas** [comment]
hm. Sorry was my bad. Never had this error before. I wont create branches in that naming style `something/something`.

Be we still can push to this branch. Hopefully we don't get this anymore when we are done with this PR #4 
if the error is still there we will have to investigate further
