### ISSUE TITLE
.here file should not be added

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/fhpredict#8]
The build process puts out the following information.

```plain
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .here

```
According to https://cran.r-project.org/doc/manuals/r-release/R-exts.html

> 1.1 Package structure
> Except where specifically mentioned,[^3] packages should not contain Unix-style ‘hidden’ files/directories (that is, those whose name starts with a dot).
> [^3]: currently, top-level files .Rbuildignore and .Rinstignore, and vignettes/.install_extras.

So we should remove it.

**Comment by hsonne** [comment]
I agree.

**Comment by mrustl** [comment]
Here file is automatically added by usethis R Package https://usethis.r-lib.org/reference/create_package.html and can stay there is useful in some way.

**Comment by fabianmoronzirfas** [comment]
hm. Thanks @mrustl I just removed it. Should we add it again?
